redditclone/accounts/urls.py
from django.conf.urls import url
from . import views

# organize urls based on app name
# <form method="POST" action="{% url 'accounts:loginview' %}">
app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='loginview'),
]

redditclone/posts/urls.py
from django.conf.urls import url
from . import views

# organize urls based on app name
# <form method="POST" action="{% url 'accounts:loginview' %}">
app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
]

redditclone/redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
]

redditclone/posts/models.py
from django.db import models

# Create your models here.

redditclone/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):

    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            # Will create a user in our DB viewable in admin admin page.
            # 'username' corresponds to <input type="text" name="username" />
            # You specify key password because you are breaking order since key email was next in line.
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error': 'Username already exists.'})
            except User.DoesNotExist:
                User.objects.create_user(request.POST['username'], password=request.POST['password1']) 
                login(request, user) # Instantly signs user in. Helps prevent logging into admin page as a user without admin creds.
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords didn\'t match.'})
    else: # Load page for the first time.
        return render(request, 'accounts/signup.html')

def loginview(request):

    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return render(request, 'accounts/login.html', {'error': 'Logged in successfully.'})
        else:
            return render(request, 'accounts/login.html', {'error': 'The username and password didn\'t match.'})
    else: # Load page for the first time.
        return render(request, 'accounts/login.html')

redditclone/posts/views.py
from django.shortcuts import render

# Create your views here.
def create(request):
    return render(request, 'posts/create.html')

redditclone/accounts/templates/accounts/login.html
<h1>Login</h1>

{% if error %}
    {{ error }}
    <br /><br />
{% endif %}

<form method="POST" action="{% url 'accounts:loginview' %}">
    {% csrf_token %}
    Username:
    <br />
    <input type="text" name="username" />
    <br />
    Password:
    <br />
    <input type="password" name="password" />
    <br />
    <input type="submit" value="Login" />
</form>

redditclone/accounts/templates/accounts/signup.html
<h1>Sign Up!</h1>

{% if error %}
    {{ error }}
    <br /><br />
{% endif %}

<form method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    Username:
    <br />
    <input type="text" name="username" />
    <br />
    Password:
    <br />
    <input type="password" name="password1" />
    <br />
    Confirm Password:
    <br />
    <input type="password" name="password2" />
    <br />
    <input type="submit" value="Sign Up!" />
</form>

redditclone/posts/templates/posts/create.html
This is the create page.